title: PICK ME UP

content: |
  Graphic identity based on three letter statements for Pick Me Up Graphic Arts Festival at Somerset House 2015.

category: |
  graphic identity, exhibition design

footnotes: |
  In collaboration with [Michael Marriott](http://www.michaelmarriott.com)