title: PLACE FAKING

content: |
  Finn Williams' exhibition at New London Architecture in 2007 included, in his words, a ‘mockumentary set 40 years after the completion of an alternative masterplan for Barking Riverside. It records residents' memories and impressions of a town built on the myth of a fictional, improved version of suburbia, a large white lie which may be fake, but﻿ ought to be true’.

  We created a leaflet for this exhibition that implies it is part of a bigger history or context by appearing to be a loose section from a larger book. The page numbers begin at 97 and the publication starts and finishes mid sentence, as if cut off from the longer running text of the book. A Doric, an Ionic and a Corinthian column hang on the exhibition spaces pre-existing display boards, whilst the remaining exhibition graphics extend into wall vinyl and captions. 

category: |
  exhibition graphics, publication

footnotes: |
  [Finn Williams](http://www.commonoffice.co.uk/), [New London Architecture](http://www.newlondonarchitecture.org/)