title: MAKERS & BROTHERS

content: |
  Makers and Brothers is an Irish shop for design and craft objects run by brothers Jonathan and Mark Legge. 

  Our graphic identity for the brothers Legge includes a series of pictograms drawn from Irish landscape and tradition. These include landscapes inspired by Paul Henry paintings, objects and animals such as a stool, a sheep and a tree, and enlarged details of materials like wood and wool. The drawings are printed on stickers and tape used for the packaging of the products. We add new pictograms for special events and the changing seasons.

category: |
  graphic identity, stationary, packaging

footnotes: |
  [Makers & Brothers](http://makersandbrothers.com/) website by [Archive](http://archivestudio.co.uk/)