title: FRONT ROOM

content: |
  Housed in Frederick Gibberd's Fullwell Cross Library the Barkingside Front Room has been designed to showcase Barkingside's past and its future as part of the ongoing 'Better Barkingside' project. It contains a growing exhibition about Barkingside, and will also host a series of events throughout the project, including lectures, celebrations, meetings and workshops.

  The maps on the walls are a growing archive of Barkingside's history, and an up-to-date record of the changes to Barkingside's public realm and frontages.

  Our bespoke typeface is based on Eurostile, the typeface used for the original signage in the library and leisure centre.

category: |
  graphic identity, exhibition

footnotes: |
  In collaboration with architects [DK-CM](http://www.dk-cm.com/)