title: BREATHING

content: |
  This book was designed on the occasion of Alice Channer's exhibition *Out of Body* at South London Gallery, using five different cuts of the typeface Univers. This book includes photographs from the exhibition, a selection of Alice's past work, an essay by Barry Schwabsky and an interview conducted by Sam Thorne. 

category: |
  book

footnotes: |
  Published by [South London Gallery](http://www.southlondongallery.org/)
