title: DK-CM

content: |
  The DK-CM identity is built with an underlying skeleton upon which a variety of typographic forms are added.

category: |
  graphic identity, logo design

footnotes: |
  [DK-CM](http://www.dk-cm.com/)