title: CONNECTORS

content: |
  *Connectors* was an exhibition of work by product designers and makers at the Saatchi Gallery. We designed the exhibition graphics including a bespoke typeface for the show.  

category: |
  exhibition graphics

footnotes: |
  Exhibition design by [Glass Hill](http://www.glasshill.co.uk/)
  [Phillips de Pury](http://www.phillipsdepury.com/)
