title: WILD KINGDOM

content: |
  The Wild Kingdom is a playspace in Three Mills Green, Newham. It includes a variety of play structures that bring a sense of unexpected adventure, a place where nature and play come together.

  Our graphic identity for the space is designed so that the community can easily implement it across a variety of platforms in print, online and on-site. As well as contributing a rugged playfulness to the project, the identity supports a number of free on-site workshops run before, during and after the landscape's construction.


category: |
  graphic identity

footnotes: |
  Playspace designed by architects [We Made That](http://www.wemadethat.co.uk/)
  Commissioned by The Legacy List and London Legacy Development Corporation 

