title: BLACKHORSE LANE INDUSTRIAL AREA

content: |
  New wayfinding for the five industrial estates along Blackhorse Lane in Walthamstow. Reusing existing posts to save cost the modular design allows flexibility and retains the possibility for additional smaller signs to be added at a later date. In addition to the signage we designed a new clock at the heart of the industrial estate. 

category: |
  signage

footnotes: |
  In collaboration with architects [We Made That](http://www.wemadethat.co.uk/)