title: CONCEPT STORE #2

category: |
  publication

content: |
  *[Concept Store](http://www.arnolfini.org.uk/pages/publications/journal)* is a journal published bi-annually by Arnolfini in Bristol. Each issue takes its theme from the current curatorial programme at the arts centre. We designed issue #2 which was about the future, spanning subjects from fashion to terrorism and from Korean housing projects to the destiny of the art world.

footnotes: |
  [Arnolfini](http://www.arnolfini.org.uk/)