title: LOOSE ASSOCIATIONS AND OTHER LECTURES

content: |
  *Loose Associations* are a series of lectures by the artist Ryan Gander. The lectures are informally structured, linking together a string of anecdotes and references into a series of happy encounters. We were asked to convert these lectures into printed form alongside three of Ryan's other lectures. We translated the narrative links into the layout by placing the images in the run of the text where they would appear as slides in the lecture.


category: |
  book

footnotes: |
  Published by [Onestar Press](http://www.onestarpress.com/)
  