title: TEMPORARY MUSEUM OF STRATFORD

content: |
  Housed in a disused lobby within the diverse Stratford Shopping Centre (not Westfield) – a place where a 24-hour public thoroughfare and market street drives through the privately owned stores of commerce – *The (Temporary) Museum of Stratford* seeks to uncover the many layers of history underlying the area's current developments, providing a reflection upon Stratford's future through an excavation of its past.

  Our brief was to design an exhibition which could be enjoyed by passers-by when peering through the windows of this forgotten corner of the shopping centre. We created the exhibition out of coloured cardboard and printed the catalogue on newsprint – temporary materials for a fleeting museum. 

  Early on in the project, when sifting through the archive material, we coincidentally found a  photograph from 1971 of a previous exhibition offering ‘glimpses into the past and future of Stratford’. This image provided inspiration and direction for many of our design decisions as well as a suitable image for the front page of the newspaper.



category: |
  exhibition design, newspaper

footnotes: |
  Part of the London Festival of Architecture, 2010
  [Architecture Foundation](http://www.architecturefoundation.org.uk/)
