title: THE ASPEN COMPLEX

content: |
  *The Aspen Complex* draws on the events of the 1970 International Design Conference in Aspen, with documentary photographs of Martin Beck's exhibition *Panel 2 – Nothing better than a touch of ecology and catastrophe to unite the social classes…*, essays by Sabeth Buchmann, Felicity D. Scott, and Alice Twemlow and video stills from the Aspen Movie Map.

  The physical form of *The Aspen Complex* references another book – *The Aspen Papers* – in both size and material. *The Aspen Papers*, published in 1974, is a book edited by Rayner Banham and designed by Ivan Chermayeff. It contains official material collected from the Aspen conferences. The headlines in *The Aspen Complex* are set in Compacta, a typeface used in two relevant counterculture publications from 1970 – *Radical Software* and *Domebook*.


category: |
  book

footnotes: |
  Designed with [Rasmus Spanggaard Troelsen](http://rasmustroelsen.dk/)
  Martin Beck and [Sternberg Press](http://www.sternberg-press.com/)