title: FUTURE WORKS


content: |
  *Future Works* is an exhibition catalogue for the Printmaking MA at the Royal College of Art. The book is printed in 8 separate 8-page signatures which are bound together, allowing one spread for each student. Each section is printed in a different complimentary colour pair which gradually changes through the book, resulting in an economical and vibrantly colourful book; a total of 16 spot pantone colours including fluorescents and metallics are used. 

  The students screenprinted the gatefold covers using their facilities at the RCA. Each cover features a marbling or blending of leftover inks from student projects. As a result traces of the artworks exhibited in the show are in the covers and each book is unique.

category: |
  catalogue

footnotes: |
  [The Royal College of Art](http://www.rca.ac.uk/)
