title: BLACKHORSE WORKSHOP

content: |
  Blackhorse Workshop is a wood and metal workshop for making and mending in Walthamstow. The workshop provides affordable access to tools and workspace for the local community.


category: |
  graphic identity, signage, [website](http://www.blackhorseworkshop.co.uk)

footnotes: |
  In collaboration with [Assemble](http://assemblestudio.co.uk)