title: GROUNDPLAN

content: |
  Groundplan is a housebuilder directed by Crispin Kelly. Central to their work is the infrastructure of shared spaces within a community and how the design of private spaces influences the public spaces in between them. 
  
  We named the company and designed their graphic identity. Our research looked at icons of British suburban living from wheelie bins to picnic benches. The identity is composed of a set of pictograms depicting items that you would be likely to find in the shared spaces of the community.

category: |
  graphic identity, stationary, [website](http://ground-plan.co.uk/)

footnotes: |
  