title: WOULDN'T IT BE NICE...

content: |
  *Wouldn't it be nice… wishful thinking in art and design* was a group exhibition curated by Katya García-Antón and Emily King. The artists and designers were chosen for having a modest sense of Utopianism in their work. They included Superflex, Bless, Alicia Framis, Jurgen Bey, Ryan Gander, Dexter Sinister, Dunne & Raby with Michael Anastassiades, Tobias Rehberger, Martí Guixé and Martino Gamper.

  The interior of this exhibition at Somerset House was designed and built utilising bespoke polystyrene structures, which were engineered using computer operated hot wires and drill bits. We were interested in using the drill bit as a drawing tool to integrate captions and wayfinding information onto the surfaces of the exhibition space. 

  We drew a typeface inspired by both old engraving typefaces by Edward Johnson and Eric Gill and the monoline engraving typefaces sometimes found on generic acrylic office signage. This meant that our monoline typeface could be used on print as well as being engraved into the polystyrene, maintaining a consistent look throughout the show.

category: |
  exhibition graphics, publication

footnotes: |
  [Somerset House](http://www.somersethouse.org.uk/)