title: FRIEZE ART FAIR FAMILY GUIDE

content: |
  ‘Just like you, Freeze Monster has been exploring Frieze Art Fair. But he has a terrible problem – he saw so much he can't actually remember what he has seen! As the fair is only once a year, this is a big problem. But, you can help!’ 

  The Family Guide is an annual activity booklet for Frieze Art Fair. Children are given a series of questions and activities to help them engage with the art at the fair. The guide is made in collaboration with the illustrator [Holly Wales](http://hollywales.com/) with texts written by Hannah Murgatroyd and Hannah Coulson.

category: |
  activity guide

footnotes: |
  [Frieze Art Fair](http://friezelondon.com/)