title: FANTASTIC FACTOLOGY

content: |
  Located in London’s Olympic Park, Fantastic Factology was a project in which facts were submitted by members of the public via the website and on postcards through various workshops. The facts were collected, edited and finally produced as a series of bench plaques which were inset in park benches dispersed throughout the site, creating a trail of informative morsels covering everything from the sleeping habits of the snail to the structure of the Mongolian language. 

category: |
  graphic identity, typeface, bench plaques, [website](http://fantastic-factology.com/)

footnotes: |
  Initiated by [The Klassnik Corporation](http://www.klassnik.com/), [Riitta Ikonen](http://www.riittaikonen.com/) and [We Made That](http://www.wemadethat.co.uk/)
  Commissioned by Olympic Delivery Authority