title: SAINT ANSELM’S

content: |
  New signage, notice board and access ramp for Saint Anselm’s Catholic Church in Southall. Part of a wider project where we were working with Ealing Council to make interventions in the public realm in Southall. The cream terrazzo replicates the terrazzo alter inside the 1968 church.

category: |
  signage

footnotes: |
  In collaboration with [DK-CM](http://www.dk-cm.com/), [Project Centre](http://www.projectcentre.co.uk/) and [Urban Movement](http://www.urbanmovement.co.uk/projects.html)