title: BUILDING RIGHTS

content: |
  Launching in April 2014, Building Rights is a user-generated resource for knowledge and information about planning issues in England and Wales. It seeks to amplify and extend existing sources of knowledge available from the government and local authorities, and to increase popular engagement with the practice of planning. It seeks to increase every citizen’s knowledge of their building rights, and their ability to use them, whether they are seeking to build, to prevent building, or otherwise to play an active role in their towns and places. Building Rights is part of ‘Making Planning Popular’, a PhD by David Knight.

category: |
  graphic identity, [website](http://www.buildingrights.org/) 

footnotes: |
  In collaboration with [DK-CM](http://www.dk-cm.com/) and [Afonso Martins](http://afonsoduarte.com/)