title: TUMULT

content: |
  *Tumult* was an exhibition showing Swedish 70s political craft. The exhibition design drew heavily on familiar vernacular exhibitions of the period, while much of the work on show had a certain urgency to it but with a high level of detail and consideration. In this spirit we imagined what a set of letterforms would look like if designed by an 'activist librarian', which became a bespoke typeface for the exhibition.

category: |
  exhibition graphics, publication, headline typeface

footnotes: |
  In collaboration with [Medium](http://www.mediumism.com/)
  [Gustavsbergs Konsthall](http://www.gustavsbergskonsthall.se/), Sweden

