title: SOUTHALL MARKET WELCOME MAT

content: |
  New terrazzo entrance to Southall Market. Part of a wider project where we were working with Ealing Council to make interventions in the public realm in Southall.

category: |
  signage

footnotes: |
  In collaboration with [DK-CM](http://www.dk-cm.com/), [Project Centre](http://www.projectcentre.co.uk/) and [Urban Movement](http://www.urbanmovement.co.uk/projects.html)