title: THE ALLOTMENT

content: |
  The Allotment was a temporary restaurant at 8 Egerton Garden Mews in South Kensington. The restaurant opened for four months in the spring of 2007 and was run by Platform 2, Design Products at the Royal College of Art. The restaurant's menu and interior design evolved in three stages – this promotional poster was overprinted and updated three times to mirror this change.

category: |
  poster

footnotes: |
  [Martino Gamper](http://martinogamper.com/), [Royal College of Art](http://www.rca.ac.uk/)