title: MODERN PAINTERS

content: |
  For the 2008 exhibition of British Post-Impressionist painters at Tate Britain we designed the marketing material. The design centred around Walter Sickert's 1914 painting *Ennui*.

category: |
  posters, leaflets, newspaper adverts, invitations

footnotes: |
  [Tate Britain](http://www.tate.org.uk/visit/tate-britain)