title: MATERIAL PRESENCE

content: |
  *Material Presence* was a group exhibition at 176 Gallery including work by Laura Buckley, Myriam Holmes, Graham Hudson, James Ireland, Alexej Meschtschanow, Katja Strunz and Mark Titchner. 

  The headline lettering that we used throughout the graphic identity was our redrawing of the Architectural Alphabet – designed by Johann Steingruber in 1773. Steingruber's letters are architectural plans for palaces, none of which were ever built. Steingruber’s alphabet, like most alphabets, existed only in printed form. To give the Alphabet a new lease of life we created a CAD rendered fly-through of the building-letters. The video loop was installed in the gallery foyer introducing visitors to the exhibition. 

  Housed in a former Methodist chapel, we covered sections of the gallery facade with banners depicting 1:1 scale sections of the Architectural Alphabet.

  The publication to accompany the exhibition came in a box which contained the catalogue and an edition from each of the exhibiting artists.


category: |
  exhibition graphics, publication

footnotes: |
  [176 Gallery](http://www.zabludowiczcollection.com/london)