title: BLACKHORSE LANE 

content: |
  These billboards document and celebrate the industry and manufacturing in the Blackhorse Lane area in Walthamstow, London. These include a prop maker, specialist stone supplier, bespoke joinery manufacturer, wooden bed maker, comic book seller, metal fabricator and a fabric distributer.  

category: |
  billboards

footnotes: |
  In collaboration with photographer [Thomas Adank](http://www.thomasadank.com) and architects [We Made That](http://www.wemadethat.co.uk/)