title: (B)RYAN'S BAR

category: |
  beermats, flyers, signage, menu

content: |
  In 2010 and 2011 we ran and designed the bar at Sunday Art Fair with Ryan Gander. The event was punctuated by a series of artist cocktail hours where artists would design and mix cocktails for customers. 

  The cocktails included 'Punch' by Fiona Banner – a cocktail where the customer would attempt to down a magnum of champagne. However, there was a catch – the champagne could only be drunk from a champagne coupe whilst wearing boxing gloves and needed to be drunk in an allotted time signified by the ringing of the bell. The following year we held an art pub quiz with Bedwyr Willams as the quizmaster, putting the art knowledge of the crowd to the test.

footnotes: |
  [Sunday Art Fair](http://sunday-fair.com/)

