title: PARALLEL CARDS

content: |
  The *Parallel Cards* at first appear like a traditional pack of cards. On closer inspection however it can be seen that the playing cards have no reverse side but two picture sides – with a different card always appearing on the reverse.   

  We developed the game Parallel Black Jacks to be played with the cards. Card tournaments for the game have been held at Somerset House, Lisson Gallery and Berkeley Art Museum, USA.

  In many traditional designs, including the designs that we were using, the front face of playing cards are printed with the spot colours blue, red, yellow and black. As these colours are not so far off of the standard printing colours – cyan, magenta, yellow and black – we printed not only the cards but the accompanying leaflet which included a photograph of twins playing with the cards.

  For the second edition of the cards we inverted all of the colours on the cards.


category: |
  playing cards, card tournament

footnotes: |
  Collaboration with Ryan Gander
  Joker illustration by [Sion Ap Tomos](http://www.sap-land.co.uk/)
  [MUMOK](http://www.mumok.at/), [The Thing Quarterly](http://www.thethingquarterly.com/quarterly/issue-9-ryan-gander.html)
  