title: FOUNTAINS

content: |
  In Autumn 2010 David Batchelor installed a fountain of light above Archway tube station. The fountain remained there throughout the dark winter months until the clocks went forward again in the spring. 

  We worked with David Batchelor and Anna Hart to create a booklet of fountain paintings. From the fountains of Peterhof Palace to the Fountain of Youth depicted by Lucas Cranach the Elder, the fountains represented a selection from art and architectural history. David turned these fountain images into a series of dot paintings for the publication. The booklets were posted through the letterboxes of the 4000 closest residents the the station announcing the switching on of the artwork.


category: |
  booklet

footnotes: |
  Published by [AIR](http://www.archwayinvestigationsandresponses.org/)
  Photography by The London Sock Exchange
